name: Jekyll site CI

on:
  push:
    branches: [ master ]

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: jekyll
        uses: helaili/jekyll-action@2.1.0
        env:
          JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}
      - name: html to pdf
        uses: misaelnieto/web_to_pdf_action@master
        with:
          webPageURL: https://lenart.org.pl/
          outputFile: ./_site/cv.pdf
          usePuppeteer: true
          useScreen: true
          pdfOptions: '{"format": "A4", "margin": {"top": "10mm", "left": "8mm", "right": "8mm", "bottom": "10mm"}, "printBackground": "true", "displayHeaderFooter": "true"}'
