name: Jekyll site CI

on:
  push:
    branches: [ master ]

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: jekyll
        uses: helaili/jekyll-action@2.1.0
        env:
          JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}
