name: Jekyll site CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Jekyll 4 Build & Deploy
      uses: joshlarsen/jekyll4-deploy-gh-pages@v1.2
